const TYPE_MAP = {
    postgresql: {
        INTEGER: "INTEGER",
        INT: "INTEGER",
        BIGINT: "BIGINT",
        VARCHAR: "VARCHAR(255)",
        TEXT: "TEXT",
        BOOLEAN: "BOOLEAN",
        DATE: "DATE",
        DATETIME: "TIMESTAMP",
        TIMESTAMP: "TIMESTAMP",
        DECIMAL: "DECIMAL(10,2)",
        FLOAT: "REAL",
        DOUBLE: "DOUBLE PRECISION",
        SERIAL: "SERIAL",
        UUID: "UUID",
        JSON: "JSON",
        JSONB: "JSONB"
    },
    mysql: {
        INTEGER: "INT",
        INT: "INT",
        BIGINT: "BIGINT",
        VARCHAR: "VARCHAR(255)",
        TEXT: "TEXT",
        BOOLEAN: "BOOLEAN",
        DATE: "DATE",
        DATETIME: "DATETIME",
        TIMESTAMP: "TIMESTAMP",
        DECIMAL: "DECIMAL(10,2)",
        FLOAT: "FLOAT",
        DOUBLE: "DOUBLE",
        SERIAL: "INT AUTO_INCREMENT",
        UUID: "CHAR(36)",
        JSON: "JSON",
        JSONB: "JSON"
    },
    sqlite: {
        INTEGER: "INTEGER",
        INT: "INTEGER",
        BIGINT: "INTEGER",
        VARCHAR: "TEXT",
        TEXT: "TEXT",
        BOOLEAN: "INTEGER",
        DATE: "TEXT",
        DATETIME: "TEXT",
        TIMESTAMP: "TEXT",
        DECIMAL: "REAL",
        FLOAT: "REAL",
        DOUBLE: "REAL",
        SERIAL: "INTEGER",
        UUID: "TEXT",
        JSON: "TEXT",
        JSONB: "TEXT"
    },
    mssql: {
        INTEGER: "INT",
        INT: "INT",
        BIGINT: "BIGINT",
        VARCHAR: "VARCHAR(255)",
        TEXT: "TEXT",
        BOOLEAN: "BIT",
        DATE: "DATE",
        DATETIME: "DATETIME2",
        TIMESTAMP: "DATETIME2",
        DECIMAL: "DECIMAL(10,2)",
        FLOAT: "FLOAT",
        DOUBLE: "FLOAT",
        SERIAL: "INT IDENTITY(1,1)",
        UUID: "UNIQUEIDENTIFIER",
        JSON: "NVARCHAR(MAX)",
        JSONB: "NVARCHAR(MAX)"
    },
    oracle: {
        INTEGER: "NUMBER",
        INT: "NUMBER",
        BIGINT: "NUMBER",
        VARCHAR: "VARCHAR2(255)",
        TEXT: "CLOB",
        BOOLEAN: "NUMBER(1)",
        DATE: "DATE",
        DATETIME: "TIMESTAMP",
        TIMESTAMP: "TIMESTAMP",
        DECIMAL: "NUMBER(10,2)",
        FLOAT: "FLOAT",
        DOUBLE: "BINARY_DOUBLE",
        SERIAL: "NUMBER GENERATED BY DEFAULT AS IDENTITY",
        UUID: "VARCHAR2(36)",
        JSON: "CLOB",
        JSONB: "CLOB"
    }
};

function normalizeType(type, dialect) {
    const clean = String(type || "TEXT").trim().toUpperCase();
    const typeMatch = clean.match(/^([A-Z][A-Z0-9_ ]*?)(\s*\(([^)]*)\))?$/);
    const baseType = typeMatch?.[1]?.trim() || clean;
    const params = typeMatch?.[3] ? `(${typeMatch[3]})` : "";
    const mapped = TYPE_MAP[dialect]?.[baseType];

    if (!mapped) {
        return clean;
    }

    if (params && ["VARCHAR", "CHAR", "DECIMAL", "NUMERIC", "NUMBER", "VARCHAR2", "NVARCHAR", "NVARCHAR2"].some((item) => mapped.startsWith(item))) {
        return mapped.replace(/\([^)]*\)/, "") + params;
    }

    return mapped;
}

function getTableNameById(nodes, id) {
    return nodes.find((node) => node.id === id)?.data?.name;
}

function getFieldByHandle(node, handleId) {
    if (!node || !handleId) {
        return null;
    }

    const fieldId = handleId
        .replace("source-", "")
        .replace("target-", "");

    return node.data.fields.find((field) => field.id === fieldId);
}

function formatRecordValue(value) {
    if (value === null || value === undefined) {
        return "null";
    }

    if (typeof value === "number" || typeof value === "boolean") {
        return String(value);
    }

    return `'${String(value).replace(/\\/g, "\\\\").replace(/'/g, "\\'")}'`;
}

function quoteIdentifier(identifier, dialect) {
    const clean = String(identifier || "unnamed")
        .trim()
        .replace(/\s+/g, "_");

    if (dialect === "mysql") {
        return `\`${clean.replace(/`/g, "``")}\``;
    }

    if (dialect === "mssql") {
        return `[${clean.replace(/]/g, "]]")}]`;
    }

    return `"${clean.replace(/"/g, "\"\"")}"`;
}

function buildIndexName(tableName, indexItem, indexNumber) {
    const columns = Array.isArray(indexItem.columns) ? indexItem.columns : [];
    const fallback = `idx_${tableName}_${columns.join("_") || indexNumber}`;

    return String(indexItem.name || fallback)
        .trim()
        .replace(/\s+/g, "_");
}

export function generateSQL(nodes, edges, dialect = "postgresql") {
    const tableStatements = nodes.map((node) => {
        const table = node.data;
        const primaryKeys = table.fields.filter((field) => field.pk).map((field) => field.name);
        const tableName = quoteIdentifier(table.name, dialect);

        const columns = table.fields.map((field) => {
            const parts = [
                `  ${quoteIdentifier(field.name, dialect)}`,
                normalizeType(field.type, dialect)
            ];

            if (!field.nullable) {
                parts.push("NOT NULL");
            }

            if (field.unique && !field.pk) {
                parts.push("UNIQUE");
            }

            return parts.join(" ");
        });

        if (primaryKeys.length > 0) {
            columns.push(`  PRIMARY KEY (${primaryKeys.map((fieldName) => quoteIdentifier(fieldName, dialect)).join(", ")})`);
        }

        const foreignKeys = edges
            .filter((edge) => edge.target === node.id)
            .map((edge) => {
                const sourceNode = nodes.find((item) => item.id === edge.source);
                const targetNode = nodes.find((item) => item.id === edge.target);

                const sourceField = getFieldByHandle(sourceNode, edge.sourceHandle);
                const targetField = getFieldByHandle(targetNode, edge.targetHandle);

                if (!sourceNode || !targetNode || !sourceField || !targetField) {
                    return null;
                }

                const sourceTableName = getTableNameById(nodes, edge.source);

                return `  FOREIGN KEY (${quoteIdentifier(targetField.name, dialect)}) REFERENCES ${quoteIdentifier(sourceTableName, dialect)}(${quoteIdentifier(sourceField.name, dialect)})`;
            })
            .filter(Boolean);

        columns.push(...foreignKeys);

        return `CREATE TABLE ${tableName} (\n${columns.join(",\n")}\n);`;
    });

    const indexStatements = nodes.flatMap((node) => {
        const table = node.data;
        const indexes = Array.isArray(table.indexes) ? table.indexes : [];

        return indexes
            .map((indexItem, indexNumber) => {
                const columns = Array.isArray(indexItem.columns)
                    ? indexItem.columns.filter((column) => table.fields.some((field) => field.name === column))
                    : [];

                if (columns.length === 0) {
                    return "";
                }

                const unique = indexItem.unique ? "UNIQUE " : "";
                const indexName = buildIndexName(table.name, indexItem, indexNumber + 1);

                return `CREATE ${unique}INDEX ${quoteIdentifier(indexName, dialect)} ON ${quoteIdentifier(table.name, dialect)} (${columns.map((column) => quoteIdentifier(column, dialect)).join(", ")});`;
            })
            .filter(Boolean);
    });

    return [...tableStatements, ...indexStatements].join("\n\n");
}

export function generateDBML(nodes, edges) {
    const tableBlocks = nodes.map((node) => {
        const lines = node.data.fields.map((field) => {
            const flags = [];

            if (field.pk) flags.push("pk");
            if (field.fk) flags.push("fk");
            if (field.unique) flags.push("unique");
            if (!field.nullable) flags.push("not null");

            return `  ${field.name} ${field.type}${flags.length ? ` [${flags.join(", ")}]` : ""}`;
        });

        const indexes = Array.isArray(node.data.indexes) ? node.data.indexes : [];
        const indexLines = indexes
            .map((indexItem, indexNumber) => {
                const columns = Array.isArray(indexItem.columns)
                    ? indexItem.columns.filter(Boolean)
                    : [];

                if (columns.length === 0) {
                    return "";
                }

                const name = indexItem.name || `idx_${node.data.name}_${columns.join("_") || indexNumber + 1}`;
                const columnsPart = columns.length === 1 ? columns[0] : `(${columns.join(", ")})`;
                const flags = indexItem.unique ? " [unique]" : "";

                return `    ${name} ${columnsPart}${flags}`;
            })
            .filter(Boolean);

        if (indexLines.length > 0) {
            lines.push("", "  Indexes {", ...indexLines, "  }");
        }

        return `Table ${node.data.name} {\n${lines.join("\n")}\n}`;
    });

    const relationLines = edges.map((edge) => {
        const sourceNode = nodes.find((node) => node.id === edge.source);
        const targetNode = nodes.find((node) => node.id === edge.target);

        const sourceField = getFieldByHandle(sourceNode, edge.sourceHandle);
        const targetField = getFieldByHandle(targetNode, edge.targetHandle);

        if (!sourceNode || !targetNode || !sourceField || !targetField) {
            return "";
        }

        const type = edge.data?.relationType || "one-to-many";

        return `Ref ${type}: ${sourceNode.data.name}.${sourceField.name} > ${targetNode.data.name}.${targetField.name}`;
    }).filter(Boolean);

    const recordBlocks = nodes
        .map((node) => {
            const records = node.data.records;
            const columns = Array.isArray(records?.columns) ? records.columns : [];
            const rows = Array.isArray(records?.rows) ? records.rows : [];

            if (columns.length === 0 || rows.length === 0) {
                return "";
            }

            const rowLines = rows.map((row) => {
                const values = Array.isArray(row) ? row : [];

                return `  ${values.map(formatRecordValue).join(", ")}`;
            });

            return `Records ${node.data.name}(${columns.join(", ")}) {\n${rowLines.join("\n")}\n}`;
        })
        .filter(Boolean);

    return [...tableBlocks, ...relationLines, ...recordBlocks].join("\n\n");
}
