const TYPE_MAP = {
    postgresql: {
        INTEGER: "INTEGER",
        INT: "INTEGER",
        BIGINT: "BIGINT",
        VARCHAR: "VARCHAR(255)",
        TEXT: "TEXT",
        BOOLEAN: "BOOLEAN",
        DATE: "DATE",
        DATETIME: "TIMESTAMP",
        TIMESTAMP: "TIMESTAMP",
        DECIMAL: "DECIMAL(10,2)",
        FLOAT: "REAL",
        DOUBLE: "DOUBLE PRECISION",
        SERIAL: "SERIAL",
        UUID: "UUID",
        JSON: "JSON",
        JSONB: "JSONB"
    },
    mysql: {
        INTEGER: "INT",
        INT: "INT",
        BIGINT: "BIGINT",
        VARCHAR: "VARCHAR(255)",
        TEXT: "TEXT",
        BOOLEAN: "BOOLEAN",
        DATE: "DATE",
        DATETIME: "DATETIME",
        TIMESTAMP: "TIMESTAMP",
        DECIMAL: "DECIMAL(10,2)",
        FLOAT: "FLOAT",
        DOUBLE: "DOUBLE",
        SERIAL: "INT AUTO_INCREMENT",
        UUID: "CHAR(36)",
        JSON: "JSON",
        JSONB: "JSON"
    },
    sqlite: {
        INTEGER: "INTEGER",
        INT: "INTEGER",
        BIGINT: "INTEGER",
        VARCHAR: "TEXT",
        TEXT: "TEXT",
        BOOLEAN: "INTEGER",
        DATE: "TEXT",
        DATETIME: "TEXT",
        TIMESTAMP: "TEXT",
        DECIMAL: "REAL",
        FLOAT: "REAL",
        DOUBLE: "REAL",
        SERIAL: "INTEGER",
        UUID: "TEXT",
        JSON: "TEXT",
        JSONB: "TEXT"
    },
    mssql: {
        INTEGER: "INT",
        INT: "INT",
        BIGINT: "BIGINT",
        VARCHAR: "VARCHAR(255)",
        TEXT: "TEXT",
        BOOLEAN: "BIT",
        DATE: "DATE",
        DATETIME: "DATETIME2",
        TIMESTAMP: "DATETIME2",
        DECIMAL: "DECIMAL(10,2)",
        FLOAT: "FLOAT",
        DOUBLE: "FLOAT",
        SERIAL: "INT IDENTITY(1,1)",
        UUID: "UNIQUEIDENTIFIER",
        JSON: "NVARCHAR(MAX)",
        JSONB: "NVARCHAR(MAX)"
    },
    oracle: {
        INTEGER: "NUMBER",
        INT: "NUMBER",
        BIGINT: "NUMBER",
        VARCHAR: "VARCHAR2(255)",
        TEXT: "CLOB",
        BOOLEAN: "NUMBER(1)",
        DATE: "DATE",
        DATETIME: "TIMESTAMP",
        TIMESTAMP: "TIMESTAMP",
        DECIMAL: "NUMBER(10,2)",
        FLOAT: "FLOAT",
        DOUBLE: "BINARY_DOUBLE",
        SERIAL: "NUMBER GENERATED BY DEFAULT AS IDENTITY",
        UUID: "VARCHAR2(36)",
        JSON: "CLOB",
        JSONB: "CLOB"
    }
};

// Тип из редактора переводим в конкретный SQL-диалект, сохраняя явно заданные
// пользователем параметры вроде VARCHAR(120) или DECIMAL(12,4).
function normalizeType(type, dialect) {
    const clean = String(type || "TEXT").trim().toUpperCase();
    const typeMatch = clean.match(/^([A-Z][A-Z0-9_ ]*?)(\s*\(([^)]*)\))?$/);
    const baseType = typeMatch?.[1]?.trim() || clean;
    const params = typeMatch?.[3] ? `(${typeMatch[3]})` : "";
    const mapped = TYPE_MAP[dialect]?.[baseType];

    if (!mapped) {
        return clean;
    }

    if (params && ["VARCHAR", "CHAR", "DECIMAL", "NUMERIC", "NUMBER", "VARCHAR2", "NVARCHAR", "NVARCHAR2"].some((item) => mapped.startsWith(item))) {
        return mapped.replace(/\([^)]*\)/, "") + params;
    }

    return mapped;
}

// Edges ссылаются на node id, а SQL generator пишет имена таблиц.
function getTableNameById(nodes, id) {
    return nodes.find((node) => node.id === id)?.data?.name;
}

// Handle содержит id поля с техническим префиксом source/target.
function getFieldByHandle(node, handleId) {
    if (!node || !handleId) {
        return null;
    }

    const fieldId = handleId
        .replace("source-", "")
        .replace("target-", "");

    return node.data.fields.find((field) => field.id === fieldId);
}

// Базовый тип без `(params)` нужен для специальных правил Records.
function getBaseType(type) {
    const clean = String(type || "TEXT").trim().toUpperCase();
    const typeMatch = clean.match(/^([A-Z][A-Z0-9_ ]*?)(\s*\(([^)]*)\))?$/);

    return typeMatch?.[1]?.trim() || clean;
}

// В DBML-like Records строки экранируются своим легким форматом.
function formatDbmlRecordValue(value) {
    if (value === null || value === undefined) {
        return "null";
    }

    if (typeof value === "number" || typeof value === "boolean") {
        return String(value);
    }

    return `'${String(value).replace(/\\/g, "\\\\").replace(/'/g, "\\'")}'`;
}

// Для SQL string literal одинарная кавычка дублируется.
function escapeSqlString(value) {
    return String(value).replace(/'/g, "''");
}

// Отдельно распознаем DATE literal без времени.
function isDateLiteral(value) {
    return /^\d{4}-\d{2}-\d{2}$/.test(value);
}

// Editor хранит preview datetime строкой, поэтому pattern проверяем явно.
function isDateTimeLiteral(value) {
    return /^\d{4}-\d{2}-\d{2}[ T]\d{2}:\d{2}:\d{2}$/.test(value);
}

/**
 * Дата и timestamp пишутся по-разному в диалектах: PostgreSQL и Oracle
 * понимают typed literals, а MSSQL получает ISO-like datetime строку.
 */
function formatTemporalSqlValue(value, baseType, dialect) {
    const normalized = String(value).replace("T", " ");

    if (baseType === "DATE" && isDateLiteral(normalized)) {
        if (dialect === "postgresql" || dialect === "oracle") {
            return `DATE '${escapeSqlString(normalized)}'`;
        }

        return `'${escapeSqlString(normalized)}'`;
    }

    if (
        ["DATETIME", "DATETIME2", "TIMESTAMP", "TIMESTAMPTZ"].includes(baseType)
        && isDateTimeLiteral(normalized)
    ) {
        if (dialect === "postgresql" || dialect === "oracle") {
            return `TIMESTAMP '${escapeSqlString(normalized)}'`;
        }

        if (dialect === "mssql") {
            return `'${escapeSqlString(normalized.replace(" ", "T"))}'`;
        }

        return `'${escapeSqlString(normalized)}'`;
    }

    return `'${escapeSqlString(value)}'`;
}

/**
 * Преобразуем значение Records в SQL literal с учетом типа поля и dialect.
 * Здесь сходятся null, boolean, даты, объекты JSON и обычные строки.
 */
function formatSqlRecordValue(value, field, dialect) {
    if (value === null || value === undefined) {
        return "NULL";
    }

    if (typeof value === "number") {
        return Number.isFinite(value) ? String(value) : "NULL";
    }

    if (typeof value === "boolean") {
        if (dialect === "mssql" || dialect === "oracle") {
            return value ? "1" : "0";
        }

        return value ? "TRUE" : "FALSE";
    }

    if (Array.isArray(value) || (typeof value === "object" && value !== null)) {
        return `'${escapeSqlString(JSON.stringify(value))}'`;
    }

    const stringValue = String(value);
    const baseType = getBaseType(field?.type);

    if (["DATE", "DATETIME", "DATETIME2", "TIMESTAMP", "TIMESTAMPTZ"].includes(baseType)) {
        return formatTemporalSqlValue(stringValue, baseType, dialect);
    }

    return `'${escapeSqlString(stringValue)}'`;
}

// Имена таблиц, колонок и индексов цитируются правилами выбранной СУБД.
function quoteIdentifier(identifier, dialect) {
    const clean = String(identifier || "unnamed")
        .trim()
        .replace(/\s+/g, "_");

    if (dialect === "mysql") {
        return `\`${clean.replace(/`/g, "``")}\``;
    }

    if (dialect === "mssql") {
        return `[${clean.replace(/]/g, "]]")}]`;
    }

    return `"${clean.replace(/"/g, "\"\"")}"`;
}

// Пустому имени индекса даем стабильный читаемый fallback для экспорта.
function buildIndexName(tableName, indexItem, indexNumber) {
    const columns = Array.isArray(indexItem.columns) ? indexItem.columns : [];
    const fallback = `idx_${tableName}_${columns.join("_") || indexNumber}`;

    return String(indexItem.name || fallback)
        .trim()
        .replace(/\s+/g, "_");
}

// Сравниваем состав индекса по порядку колонок.
function sameColumnList(left, right) {
    return left.length === right.length
        && left.every((column, index) => column === right[index]);
}

// Не дублируем индекс, который уже покрыт primary key или unique field.
function isRedundantIndex(table, indexItem, columns) {
    const primaryKeys = table.fields
        .filter((field) => field.pk)
        .map((field) => field.name);

    if (columns.length > 0 && sameColumnList(columns, primaryKeys)) {
        return true;
    }

    if (columns.length !== 1) {
        return false;
    }

    const field = table.fields.find((item) => item.name === columns[0]);

    if (!field) {
        return false;
    }

    if (field.pk) {
        return true;
    }

    return Boolean(indexItem.unique && field.unique);
}

// Родительские таблицы идут раньше FK-таблиц, чтобы экспорт было проще выполнять в чистой БД.
/**
 * INSERT и CREATE TABLE удобнее выводить от родителей к зависимым таблицам.
 * Для циклов сохраняем оставшиеся таблицы в исходном порядке.
 */
function sortTableNodesByDependencies(tableNodes, edges) {
    const nodesById = new Map(tableNodes.map((node) => [node.id, node]));
    const adjacency = new Map();
    const indegree = new Map();

    // Готовим graph dependency: каждая таблица начинает с нулевого числа родителей.
    tableNodes.forEach((node) => {
        adjacency.set(node.id, new Set());
        indegree.set(node.id, 0);
    });

    // Edge идет от referenced table к таблице с FK, значит target зависит от source.
    edges.forEach((edge) => {
        if (!nodesById.has(edge.source) || !nodesById.has(edge.target)) {
            return;
        }

        const sourceNeighbors = adjacency.get(edge.source);

        if (!sourceNeighbors.has(edge.target)) {
            sourceNeighbors.add(edge.target);
            indegree.set(edge.target, (indegree.get(edge.target) || 0) + 1);
        }
    });

    // Начинаем с таблиц без зависимостей и снимаем indegree у дочерних таблиц.
    const queue = tableNodes
        .filter((node) => (indegree.get(node.id) || 0) === 0);
    const ordered = [];

    while (queue.length > 0) {
        const current = queue.shift();
        ordered.push(current);

        adjacency.get(current.id).forEach((neighborId) => {
            const nextIndegree = (indegree.get(neighborId) || 0) - 1;
            indegree.set(neighborId, nextIndegree);

            if (nextIndegree === 0) {
                queue.push(nodesById.get(neighborId));
            }
        });
    }

    if (ordered.length === tableNodes.length) {
        return ordered;
    }

    // Циклические FK не имеют полного topological order, но экспорт все равно должен вернуть DDL.
    const orderedIds = new Set(ordered.map((node) => node.id));

    return [
        ...ordered,
        ...tableNodes.filter((node) => !orderedIds.has(node.id))
    ];
}

/**
 * Преобразует preview-records таблицы в INSERT.
 * Колонки без соответствующего поля пропускаются, чтобы старый snapshot не ломал экспорт.
 */
// Preview Records превращаются в INSERT, только если есть колонки и строки.
function buildInsertStatements(node, dialect) {
    const table = node.data;
    const records = table.records;
    const columns = Array.isArray(records?.columns) ? records.columns : [];
    const rows = Array.isArray(records?.rows) ? records.rows : [];

    if (columns.length === 0 || rows.length === 0) {
        return [];
    }

    // Records может пережить удаление поля, поэтому сперва отбрасываем устаревшие колонки.
    const fieldsByName = new Map(table.fields.map((field) => [field.name, field]));
    const validColumns = columns
        .map((column, index) => ({ column, index }))
        .filter(({ column }) => fieldsByName.has(column));

    if (validColumns.length === 0) {
        return [];
    }

    const tableName = quoteIdentifier(table.name, dialect);
    const columnList = validColumns
        .map(({ column }) => quoteIdentifier(column, dialect))
        .join(", ");
    const insertStatements = rows.map((row) => {
        const values = validColumns.map(({ column, index }) => {
            const field = fieldsByName.get(column);
            const rawValue = Array.isArray(row) ? row[index] : null;

            return formatSqlRecordValue(rawValue, field, dialect);
        });

        return `INSERT INTO ${tableName} (${columnList}) VALUES (${values.join(", ")});`;
    });
    // SQL Server запрещает явный INSERT в IDENTITY без отдельного переключателя.
    const usesIdentityInsert = dialect === "mssql"
        && validColumns.some(({ column }) => normalizeType(fieldsByName.get(column)?.type, dialect).includes("IDENTITY"));

    if (!usesIdentityInsert) {
        return insertStatements;
    }

    return [
        `SET IDENTITY_INSERT ${tableName} ON;`,
        ...insertStatements,
        `SET IDENTITY_INSERT ${tableName} OFF;`
    ];
}

/**
 * Генерирует исполняемый SQL из canvas-схемы:
 * CREATE TABLE сначала, затем демо-записи и отдельные CREATE INDEX.
 */
/**
 * Основной SQL export собирает таблицы, ограничения, индексы и Records
 * в скрипт выбранного диалекта.
 */
export function generateSQL(nodes, edges, dialect = "postgresql") {
    const tableNodes = nodes.filter((node) => Array.isArray(node.data?.fields));
    const orderedTableNodes = sortTableNodesByDependencies(tableNodes, edges);

    // Первая секция экспорта описывает структуру таблиц.
    const tableStatements = orderedTableNodes.map((node) => {
        const table = node.data;
        const primaryKeys = table.fields.filter((field) => field.pk).map((field) => field.name);
        const tableName = quoteIdentifier(table.name, dialect);

        const columns = table.fields.map((field) => {
            const parts = [
                `  ${quoteIdentifier(field.name, dialect)}`,
                normalizeType(field.type, dialect)
            ];

            if (!field.nullable) {
                parts.push("NOT NULL");
            }

            if (field.unique && !field.pk) {
                parts.push("UNIQUE");
            }

            return parts.join(" ");
        });

        if (primaryKeys.length > 0) {
            columns.push(`  PRIMARY KEY (${primaryKeys.map((fieldName) => quoteIdentifier(fieldName, dialect)).join(", ")})`);
        }

        // FK записываем в target-таблицу, потому что target field хранит внешний ключ.
        const foreignKeys = edges
            .filter((edge) => edge.target === node.id)
            .map((edge) => {
                const sourceNode = tableNodes.find((item) => item.id === edge.source);
                const targetNode = tableNodes.find((item) => item.id === edge.target);

                const sourceField = getFieldByHandle(sourceNode, edge.sourceHandle);
                const targetField = getFieldByHandle(targetNode, edge.targetHandle);

                if (!sourceNode || !targetNode || !sourceField || !targetField) {
                    return null;
                }

                const sourceTableName = getTableNameById(tableNodes, edge.source);

                return `  FOREIGN KEY (${quoteIdentifier(targetField.name, dialect)}) REFERENCES ${quoteIdentifier(sourceTableName, dialect)}(${quoteIdentifier(sourceField.name, dialect)})`;
            })
            .filter(Boolean);

        columns.push(...foreignKeys);

        return `CREATE TABLE ${tableName} (\n${columns.join(",\n")}\n);`;
    });

    // Демо-записи идут после DDL, когда все таблицы уже объявлены.
    const insertStatements = orderedTableNodes.flatMap((node) => buildInsertStatements(node, dialect));

    // Индексы держим отдельной секцией и не дублируем PK/unique-индексы самих полей.
    const indexStatements = orderedTableNodes.flatMap((node) => {
        const table = node.data;
        const indexes = Array.isArray(table.indexes) ? table.indexes : [];

        return indexes
            .map((indexItem, indexNumber) => {
                const columns = Array.isArray(indexItem.columns)
                    ? indexItem.columns.filter((column) => table.fields.some((field) => field.name === column))
                    : [];

                if (columns.length === 0) {
                    return "";
                }

                if (isRedundantIndex(table, indexItem, columns)) {
                    return "";
                }

                const unique = indexItem.unique ? "UNIQUE " : "";
                const indexName = buildIndexName(table.name, indexItem, indexNumber + 1);

                return `CREATE ${unique}INDEX ${quoteIdentifier(indexName, dialect)} ON ${quoteIdentifier(table.name, dialect)} (${columns.map((column) => quoteIdentifier(column, dialect)).join(", ")});`;
            })
            .filter(Boolean);
    });

    return [...tableStatements, ...insertStatements, ...indexStatements].join("\n\n");
}

/**
 * Возвращает текст, который видит встроенный DBML-like редактор.
 * Он является человекочитаемым представлением того же React Flow snapshot.
 */
/**
 * DBML-like export возвращает текстовый источник editor: Table, Indexes,
 * Records и Ref строки на основе текущего canvas snapshot.
 */
export function generateDBML(nodes, edges) {
    const tableNodes = nodes.filter((node) => Array.isArray(node.data?.fields));

    // Table-блоки содержат поля и вложенные Indexes, которые редактируются человеком.
    const tableBlocks = tableNodes.map((node) => {
        const lines = node.data.fields.map((field) => {
            const flags = [];

            if (field.pk) flags.push("pk");
            if (field.fk) flags.push("fk");
            if (field.unique) flags.push("unique");
            if (!field.nullable) flags.push("not null");

            return `  ${field.name} ${field.type}${flags.length ? ` [${flags.join(", ")}]` : ""}`;
        });

        const indexes = Array.isArray(node.data.indexes) ? node.data.indexes : [];
        const indexLines = indexes
            .map((indexItem, indexNumber) => {
                const columns = Array.isArray(indexItem.columns)
                    ? indexItem.columns.filter((column) => node.data.fields.some((field) => field.name === column))
                    : [];

                if (columns.length === 0) {
                    return "";
                }

                if (isRedundantIndex(node.data, indexItem, columns)) {
                    return "";
                }

                const name = indexItem.name || `idx_${node.data.name}_${columns.join("_") || indexNumber + 1}`;
                const columnsPart = columns.length === 1 ? columns[0] : `(${columns.join(", ")})`;
                const flags = indexItem.unique ? " [unique]" : "";

                return `    ${name} ${columnsPart}${flags}`;
            })
            .filter(Boolean);

        if (indexLines.length > 0) {
            lines.push("", "  Indexes {", ...indexLines, "  }");
        }

        return `Table ${node.data.name} {\n${lines.join("\n")}\n}`;
    });

    // После таблиц выводим Ref по именам, чтобы связь можно было поправить текстом.
    const relationLines = edges.map((edge) => {
        const sourceNode = tableNodes.find((node) => node.id === edge.source);
        const targetNode = tableNodes.find((node) => node.id === edge.target);

        const sourceField = getFieldByHandle(sourceNode, edge.sourceHandle);
        const targetField = getFieldByHandle(targetNode, edge.targetHandle);

        if (!sourceNode || !targetNode || !sourceField || !targetField) {
            return "";
        }

        const type = edge.data?.relationType || "one-to-many";

        return `Ref ${type}: ${sourceNode.data.name}.${sourceField.name} > ${targetNode.data.name}.${targetField.name}`;
    }).filter(Boolean);

    // Records остаются отдельными блоками и не смешиваются с описанием структуры таблицы.
    const recordBlocks = tableNodes
        .map((node) => {
            const records = node.data.records;
            const columns = Array.isArray(records?.columns) ? records.columns : [];
            const rows = Array.isArray(records?.rows) ? records.rows : [];

            if (columns.length === 0 || rows.length === 0) {
                return "";
            }

            const rowLines = rows.map((row) => {
                const values = Array.isArray(row) ? row : [];

                return `  ${values.map(formatDbmlRecordValue).join(", ")}`;
            });

            return `Records ${node.data.name}(${columns.join(", ")}) {\n${rowLines.join("\n")}\n}`;
        })
        .filter(Boolean);

    return [...tableBlocks, ...relationLines, ...recordBlocks].join("\n\n");
}
